version: '3.9'

services:
  db:
    ports:
      - 127.0.0.1:5432:5432
  redis:
    ports:
      - 127.0.0.1:6379:6379
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:9229:9229
    environment:
      NODE_ARGS: --inspect=0.0.0.0:9229
    command: ['yarn', '_docker']
