// pretty imcomplete, will need to change later on

export namespace Hypixel {
  export interface PlayerResponse {
    success: boolean;
    player: Player;
  }

  export interface Player {
    _id: string;
    uuid: string;
    firstLogin: number;
    playername: string;
    lastLogin: number;
    displayname: string;
    knownAliases: string[];
    knownAliasesLower: string[];
    achievementsOneTime: string[];
    mcVersionRp: string;
    stats: Stats;
    karma: number;
    networkExp: number;
    petConsumables: { [key: string]: number };
    vanityMeta: VanityMeta;
    achievements: { [key: string]: number };
    housingMeta: HousingMeta;
    voting: { [key: string]: number };
    flashingSalePoppedUp: number;
    flashingSalePopup: number;
    lastAdsenseGenerateTime: number;
    lastClaimedReward: number;
    totalRewards: number;
    totalDailyRewards: number;
    rewardStreak: number;
    rewardScore: number;
    rewardHighScore: number;
    lastLogout: number;
    network_update_book: string;
    achievementTracking: string[];
    quickjoin_timestamp: number;
    quickjoin_uses: number;
    achievementRewardsNew: { [key: string]: number };
    challenges: Challenges;
    achievementPoints: number;
    friendRequestsUuid: any[];
    parkourCheckpointBests: ParkourCheckpointBests;
    parkourCompletions: { [key: string]: ParkourCompletion[] };
    channel: string;
    achievementSync: AchievementSync;
    newPackageRank: string;
    levelUp_VIP_PLUS: number;
    levelUp_MVP_PLUS: number;
    questSettings: QuestSettings;
    petStats: { [type: string]: Pet };
    petJourneyTimestamp: number;
    adsense_tokens: number;
    socialMedia: SocialMedia;
    rankPlusColor: string;
    tourney: Tourney;
    gifts_grinch: number;
    achievementTotem: AchievementTotem;
    currentPet: string;
    currentGadget: string;
    vanityFavorites: string;
    giftingMeta: GiftingMeta;
    fortuneBuff: number;
  }

  export interface AchievementSync {
    quake_tiered: number;
  }

  export interface AchievementTotem {
    canCustomize: boolean;
    allowed_max_height: number;
    unlockedParts: string[];
    selectedParts: SelectedParts;
    unlockedColors: string[];
    selectedColors: SelectedColors;
  }

  export interface SelectedColors {
    slotcolor_0: string;
  }

  export interface SelectedParts {
    slot_0: string;
    slot_1: string;
  }

  export interface Challenges {
    all_time: { [key: string]: number };
  }

  export interface GiftingMeta {
    bundlesReceived: number;
    realBundlesReceived: number;
  }

  export interface HousingMeta {
    allowedBlocks: string[];
    tutorialStep: string;
    packages: string[];
    playerSettings: PlayerSettings;
    firstHouseJoinMs: number;
    plotSize: string;
    selectedChannels_v3: string[];
  }

  export interface PlayerSettings {
    BORDER: string;
    VISIBILITY: string;
  }

  export interface ParkourCheckpointBests {
    Duels: { [key: string]: number };
    Bedwars: { [key: string]: number };
    Prototype: { [key: string]: number };
    CopsnCrims: { [key: string]: number };
    BlitzLobby: { [key: string]: number };
    BuildBattle: { [key: string]: number };
    Warlords: { [key: string]: number };
    uhc: { [key: string]: number };
    ArcadeGames: { [key: string]: number };
    MegaWalls: { [key: string]: number };
    MurderMystery: { [key: string]: number };
    TNT: { [key: string]: number };
  }

  export interface ParkourCompletion {
    timeStart: number;
    timeTook: number;
  }

  export interface Pet {
    THIRST: PetStatus;
    HUNGER: PetStatus;
    EXERCISE: PetStatus;
    name?: string;
    experience: number;
  }

  export interface PetStatus {
    value: number;
    timestamp: number;
  }

  export interface QuestSettings {
    autoActivate: boolean;
  }

  export interface ArcadeGamer {
    completions: Completion[];
  }

  export interface Completion {
    time: number;
  }

  export interface SocialMedia {
    links: { [platform: string]: string };
    prompt: boolean;
  }

  export interface Stats {
    Arcade: Arcade;
    TNTGames: TNTGames;
    MCGO: Mcgo;
    Walls3: Walls3;
    Walls: Walls;
    HungerGames: HungerGames;
    Battleground: Battleground;
    SkyWars: SkyWars;
    TrueCombat: TrueCombat;
    Arena: Arena;
    GingerBread: GingerBread;
    SuperSmash: SuperSmash;
    Quake: Quake;
    Bedwars: Bedwars;
    MurderMystery: { [key: string]: string[] | boolean | number | string };
    BuildBattle: BuildBattle;
    Duels: Duels;
    Paintball: Paintball;
    VampireZ: VampireZ;
    Legacy: Legacy;
    SpeedUHC: SpeedUHC;
    UHC: Uhc;
    SkyClash: SkyClash;
    Pit: Pit;
    SkyBlock: SkyBlock;
    Housing: VanityMeta;
  }

  export interface Arcade {
    coins: number;
    deaths_oneinthequiver: number;
    kills_oneinthequiver: number;
    kills_dayone: number;
    headshots_dayone: number;
    time_stamp: number;
    stamp_level: number;
    music: boolean;
    rounds_santa_says: number;
    sw_deaths: number;
    sw_shots_fired: number;
    rounds_simon_says: number;
    monthly_coins_b: number;
    weekly_coins_a: number;
    kills_throw_out: number;
    deaths_throw_out: number;
    max_wave: number;
    sw_empire_kills: number;
    sw_kills: number;
    sw_weekly_kills_a: number;
    sw_monthly_kills_b: number;
    sw_weekly_kills_b: number;
    sw_rebel_kills: number;
    weekly_coins_b: number;
    monthly_coins_a: number;
    dec2016_achievements: boolean;
    dec2016_achievements2: boolean;
    wins_party: number;
    miniwalls_activeKit: string;
    final_kills_mini_walls: number;
    wins_mini_walls: number;
    deaths_mini_walls: number;
    wither_damage_mini_walls: number;
    kills_mini_walls: number;
    seeker_wins_hide_and_seek: number;
    prop_hunt_seeker_wins_hide_and_seek: number;
    party_pooper_seeker_wins_hide_and_seek: number;
    arrows_hit_mini_walls: number;
    arrows_shot_mini_walls: number;
    wither_kills_mini_walls: number;
    headshots_zombies: number;
    zombie_kills_zombies_deadend: number;
    deaths_zombies: number;
    times_knocked_down_zombies: number;
    zombie_kills_zombies: number;
    zombie_kills_zombies_deadend_normal: number;
    deaths_zombies_deadend: number;
    times_knocked_down_zombies_deadend_normal: number;
    deaths_zombies_deadend_normal: number;
    basic_zombie_kills_zombies: number;
    bullets_shot_zombies: number;
    times_knocked_down_zombies_deadend: number;
    bullets_hit_zombies: number;
    bounty_kills_oneinthequiver: number;
    hitw_record_q: number;
    rounds_hole_in_the_wall: number;
    hitw_record_f: number;
    best_round_zombies_deadend_normal: number;
    fastest_time_10_zombies_deadend_normal: number;
    best_round_zombies_deadend: number;
    fastest_time_20_zombies: number;
    best_round_zombies: number;
    fastest_time_20_zombies_deadend_normal: number;
    fastest_time_10_zombies: number;
    total_rounds_survived_zombies_deadend_normal: number;
    players_revived_zombies_deadend_normal: number;
    magma_cube_zombie_kills_zombies: number;
    skelefish_zombie_kills_zombies: number;
    guardian_zombie_kills_zombies: number;
    blaze_zombie_kills_zombies: number;
    windows_repaired_zombies_deadend: number;
    tnt_baby_zombie_kills_zombies: number;
    doors_opened_zombies_deadend_normal: number;
    magma_zombie_kills_zombies: number;
    players_revived_zombies: number;
    total_rounds_survived_zombies_deadend: number;
    fire_zombie_kills_zombies: number;
    doors_opened_zombies: number;
    total_rounds_survived_zombies: number;
    windows_repaired_zombies: number;
    wolf_zombie_kills_zombies: number;
    pig_zombie_zombie_kills_zombies: number;
    empowered_zombie_kills_zombies: number;
    windows_repaired_zombies_deadend_normal: number;
    doors_opened_zombies_deadend: number;
    players_revived_zombies_deadend: number;
    best_round_zombies_alienarcadium: number;
    best_round_zombies_alienarcadium_normal: number;
    fastest_time_10_zombies_alienarcadium_normal: number;
    rainbow_zombie_kills_zombies: number;
    space_blaster_zombie_kills_zombies: number;
    windows_repaired_zombies_alienarcadium: number;
    times_knocked_down_zombies_alienarcadium: number;
    doors_opened_zombies_alienarcadium: number;
    zombie_kills_zombies_alienarcadium_normal: number;
    worm_small_zombie_kills_zombies: number;
    deaths_zombies_alienarcadium: number;
    windows_repaired_zombies_alienarcadium_normal: number;
    worm_zombie_kills_zombies: number;
    total_rounds_survived_zombies_alienarcadium_normal: number;
    times_knocked_down_zombies_alienarcadium_normal: number;
    total_rounds_survived_zombies_alienarcadium: number;
    sentinel_zombie_kills_zombies: number;
    players_revived_zombies_alienarcadium: number;
    doors_opened_zombies_alienarcadium_normal: number;
    zombie_kills_zombies_alienarcadium: number;
    deaths_zombies_alienarcadium_normal: number;
    space_grunt_zombie_kills_zombies: number;
    skeleton_zombie_kills_zombies: number;
    blob_zombie_kills_zombies: number;
    players_revived_zombies_alienarcadium_normal: number;
    packages: string[];
    melee_weapon: string;
    dtt_dropdown: boolean;
    wins_simon_says: number;
    kills_dragonwars2: number;
    powerkicks_soccer: number;
    kicks_soccer: number;
    clown_zombie_kills_zombies: number;
    dtt_music: boolean;
    dtt_filter: boolean;
    wins_soccer: number;
    goals_soccer: number;
    showinfobook: boolean;
    hider_wins_hide_and_seek: number;
    party_pooper_hider_wins_hide_and_seek: number;
    poop_collected: number;
    wins_farm_hunt: number;
    wins_throw_out: number;
    items_found_scuba_simulator: number;
    total_points_scuba_simulator: number;
    candy_found_halloween_simulator: number;
    wins_grinch_simulator_v2: number;
    lastTourneyAd: number;
    gifts_grinch_simulator_v2_tourney: number;
    wins_grinch_simulator_v2_tourney: number;
    losses_grinch_simulator_v2_tourney: number;
  }

  export interface Arena {
    rating: number;
    win_streaks_1v1: number;
    damage_1v1: number;
    games_1v1: number;
    losses_1v1: number;
    healed_1v1: number;
    coins: number;
    win_streaks_4v4: number;
    losses_4v4: number;
    healed_4v4: number;
    damage_4v4: number;
    deaths_4v4: number;
    games_4v4: number;
    deaths_1v1: number;
    offensive: string;
    utility: string;
    ultimate: string;
    keys: number;
    kills_1v1: number;
    wins: number;
    wins_1v1: number;
    support: string;
  }

  export interface Battleground {
    mage_spec: string;
    warrior_spec: string;
    paladin_spec: string;
    selected_mount: string;
    shaman_spec: string;
    packages: string[];
    coins: number;
    chosen_class: string;
    win_streak: number;
    play_streak: number;
    damage_pyromancer: number;
    damage_mage: number;
    heal_pyromancer: number;
    deaths: number;
    powerups_collected: number;
    damage_prevented: number;
    damage_prevented_pyromancer: number;
    wins_domination: number;
    wins_red: number;
    mage_plays: number;
    heal: number;
    wins: number;
    damage_prevented_mage: number;
    heal_mage: number;
    dom_point_captures: number;
    total_domination_score: number;
    pyromancer_plays: number;
    damage: number;
    wins_pyromancer: number;
    wins_mage: number;
    wins_domination_red: number;
    assists: number;
    wins_domination_a: number;
    damage_taken: number;
    broken_inventory: number;
    hotkeymode: boolean;
    simplifiedresourcepack: boolean;
    hide_prestige: boolean;
  }

  export interface SkyWars {
    active_balloon: string;
    active_cage: string;
    active_deathcry: string;
    active_killeffect: string;
    active_killmessages: string;
    active_projectiletrail: string;
    active_sprays: string;
    active_victorydance: string;
    activeKit_MEGA: string;
    activeKit_RANKED: string;
    activeKit_RANKED_random: boolean;
    activeKit_SOLO: string;
    activeKit_SOLO_random: boolean;
    activeKit_TEAM: string;
    activeKit_TEAMS: string;
    activeKit_TEAMS_random: boolean;
    arrows_hit: number;
    arrows_hit_lab: number;
    arrows_hit_lab_solo: number;
    arrows_hit_ranked: number;
    arrows_hit_solo: number;
    arrows_hit_team: number;
    arrows_shot: number;
    arrows_shot_lab: number;
    arrows_shot_lab_solo: number;
    arrows_shot_ranked: number;
    arrows_shot_solo: number;
    arrows_shot_team: number;
    assists: number;
    assists_mega: number;
    assists_ranked: number;
    assists_solo: number;
    assists_team: number;
    blocks_broken: number;
    blocks_placed: number;
    blocks_placed_lab: number;
    bow_kills: number;
    bow_kills_solo: number;
    bow_kills_team: number;
    chests_opened: number;
    chests_opened_lab: number;
    chests_opened_lab_solo: number;
    chests_opened_mega: number;
    chests_opened_ranked: number;
    chests_opened_solo: number;
    chests_opened_team: number;
    coins: number;
    coins_gained_lab: number;
    cosmetic_tokens: number;
    deaths: number;
    deaths_lab: number;
    deaths_lab_solo: number;
    deaths_mega: number;
    deaths_mega_normal: number;
    deaths_ranked: number;
    deaths_ranked_normal: number;
    deaths_solo: number;
    deaths_solo_insane: number;
    deaths_solo_normal: number;
    deaths_team: number;
    deaths_team_insane: number;
    deaths_team_normal: number;
    egg_thrown: number;
    egg_thrown_lab: number;
    enderpearls_thrown: number;
    extra_wheels: number;
    fastest_win: number;
    fastest_win_ranked: number;
    fastest_win_solo: number;
    fastest_win_team: number;
    freeLootChestNpc: number;
    games: number;
    games_mega: number;
    games_played_skywars: number;
    games_ranked: number;
    games_solo: number;
    games_team: number;
    heads: number;
    heads_decent: number;
    heads_decent_team: number;
    highestKillstreak: number;
    highestWinstreak: number;
    inGamePresentsCap_2019_3: number;
    inGamePresentsCap_2019_6: number;
    inGamePresentsCap_2019_8: number;
    inGamePresentsCap_2019_22: number;
    inGamePresentsCap_2020_2: number;
    inGamePresentsCap_2020_4: number;
    inGamePresentsCap_2020_11: number;
    items_enchanted: number;
    kills: number;
    kills_lab: number;
    kills_lab_solo: number;
    kills_mega: number;
    kills_mega_normal: number;
    kills_monthly_a: number;
    kills_monthly_b: number;
    kills_ranked: number;
    kills_ranked_normal: number;
    kills_solo: number;
    kills_solo_insane: number;
    kills_solo_normal: number;
    kills_team: number;
    kills_team_insane: number;
    kills_weekly_a: number;
    kills_weekly_b: number;
    killstreak: number;
    killstreak_ranked: number;
    killstreak_solo: number;
    killstreak_team: number;
    lastMode: string;
    levelFormatted: string;
    longest_bow_kill: number;
    longest_bow_kill_lab: number;
    longest_bow_kill_lab_solo: number;
    longest_bow_kill_ranked: number;
    longest_bow_kill_solo: number;
    longest_bow_kill_team: number;
    longest_bow_shot: number;
    longest_bow_shot_lab: number;
    longest_bow_shot_lab_solo: number;
    longest_bow_shot_ranked: number;
    longest_bow_shot_solo: number;
    longest_bow_shot_team: number;
    losses: number;
    losses_lab: number;
    losses_lab_solo: number;
    losses_mega: number;
    losses_mega_normal: number;
    losses_ranked: number;
    losses_ranked_normal: number;
    losses_solo: number;
    losses_solo_insane: number;
    losses_solo_normal: number;
    losses_team: number;
    losses_team_insane: number;
    losses_team_normal: number;
    lucky_explained: number;
    lucky_explained_last: number;
    luckyBlockResourcePackEnabled: boolean;
    mega_black_magic: number;
    mega_bridger: number;
    mega_ender_mastery: number;
    mega_instant_smelting: number;
    mega_lucky_charm: number;
    mega_mining_expertise: number;
    mega_nourishment: number;
    mega_rusher: number;
    melee_kills: number;
    melee_kills_lab: number;
    melee_kills_lab_solo: number;
    melee_kills_ranked: number;
    melee_kills_solo: number;
    melee_kills_team: number;
    mob_kills: number;
    mob_kills_solo: number;
    most_kills_game: number;
    most_kills_game_lab: number;
    most_kills_game_lab_solo: number;
    most_kills_game_ranked: number;
    most_kills_game_solo: number;
    most_kills_game_team: number;
    packages: string[];
    paid_souls: number;
    quits: number;
    quits_lab: number;
    refill_chest_destroy: number;
    shop_sort: string;
    shop_sort_enable_owned_first: boolean;
    skywars_chest_history: string[];
    skywars_chests: number;
    skywars_christmas_boxes: number;
    skywars_experience: number;
    skywars_halloween_boxes: number;
    SkyWars_openedChests: number;
    SkyWars_openedCommons: number;
    SkyWars_openedEpics: number;
    SkyWars_openedRares: number;
    slime_explained: number;
    slime_explained_last: number;
    solo_bridger: number;
    solo_ender_mastery: number;
    solo_fat: number;
    solo_knowledge: number;
    solo_lucky_charm: number;
    solo_marksmanship: number;
    solo_mining_expertise: number;
    solo_nourishment: number;
    solo_resistance_boost: number;
    solo_speed_boost: number;
    soul_well: number;
    soul_well_legendaries: number;
    soul_well_rares: number;
    souls: number;
    souls_gathered: number;
    survived_players: number;
    survived_players_lab: number;
    survived_players_lab_solo: number;
    survived_players_mega: number;
    survived_players_ranked: number;
    survived_players_solo: number;
    survived_players_team: number;
    team_arrow_recovery: number;
    team_bridger: number;
    team_bulldozer: number;
    team_ender_mastery: number;
    team_instant_smelting: number;
    team_juggernaut: number;
    team_knowledge: number;
    team_lucky_charm: number;
    team_mining_expertise: number;
    team_necromancer: number;
    team_nourishment: number;
    team_resistance_boost: number;
    team_savior: number;
    time_played: number;
    time_played_lab: number;
    time_played_lab_solo: number;
    time_played_mega: number;
    time_played_ranked: number;
    time_played_solo: number;
    time_played_team: number;
    tnt_madness_explained: number;
    tnt_madness_explained_last: number;
    toggle_team_necromancer: boolean;
    usedSoulWell: boolean;
    void_kills: number;
    void_kills_ranked: number;
    void_kills_solo: number;
    void_kills_team: number;
    win_streak: number;
    win_streak_lab: number;
    wins: number;
    wins_ranked: number;
    wins_ranked_normal: number;
    wins_solo: number;
    wins_solo_insane: number;
    wins_solo_normal: number;
    wins_team: number;
    wins_team_insane: number;
    winstreak: number;
  }

  export interface BuildBattle {
    wins_solo_normal: number;
    wins: number;
    teams_most_points: number;
    games_played: number;
    score: number;
    monthly_coins_b: number;
    coins: number;
    weekly_coins_b: number;
    total_votes: number;
    votes_World: number;
    monthly_coins_a: number;
    weekly_coins_a: number;
    music: boolean;
    correct_guesses: number;
    wins_guess_the_build: number;
  }

  export interface Duels {
    duels_recently_played: string;
    selected_1_new: string;
    selected_2_new: string;
    games_played_duels: number;
    show_lb_option: string;
    current_op_winstreak: number;
    best_overall_winstreak: number;
    current_winstreak: number;
    best_op_winstreak: number;
    duels_winstreak_best_op_doubles: number;
    chat_enabled: string;
    op_doubles_health_regenerated: number;
    melee_swings: number;
    op_doubles_melee_hits: number;
    melee_hits: number;
    op_doubles_wins: number;
    wins: number;
    rounds_played: number;
    op_doubles_rounds_played: number;
    kills: number;
    coins: number;
    op_doubles_kills: number;
    op_doubles_damage_dealt: number;
    health_regenerated: number;
    damage_dealt: number;
    op_doubles_melee_swings: number;
    sw_duels_kit_new: string;
    best_skywars_winstreak: number;
    current_skywars_winstreak: number;
    kit_wins: number;
    sw_doubles_armorer_kit_wins: number;
    sw_doubles_rounds_played: number;
    sw_doubles_wins: number;
    sw_doubles_kit_wins: number;
    armorer_kit_wins: number;
    rematch_option_1: string;
    losses: number;
    deaths: number;
    sw_doubles_health_regenerated: number;
    sw_doubles_deaths: number;
    sw_doubles_losses: number;
    duels_winstreak_best_sw_doubles: number;
    sw_doubles_melee_swings: number;
    sw_doubles_kills: number;
    sw_doubles_melee_hits: number;
    sw_doubles_damage_dealt: number;
    bridge_duel_deaths: number;
    goals: number;
    bridge_duel_goals: number;
    bridge_2v2v2v2_wins: number;
    bridge_2v2v2v2_losses: number;
    bridge_2v2v2v2_rounds_played: number;
    bridge_duel_kills: number;
    bridge_2v2v2v2_goals: number;
    bridge_2v2v2v2_kills: number;
    bridge_duel_losses: number;
    bridge_2v2v2v2_deaths: number;
    bridge_duel_rounds_played: number;
    uhc_duel_health_regenerated: number;
    uhc_duel_rounds_played: number;
    uhc_duel_damage_dealt: number;
    uhc_duel_bow_shots: number;
    uhc_duel_melee_swings: number;
    uhc_duel_melee_hits: number;
    bow_shots: number;
    blocks_placed: number;
    uhc_duel_bow_hits: number;
    bow_hits: number;
    uhc_duel_blocks_placed: number;
    blitz_rookie_title_prestige: number;
    mega_walls_rookie_title_prestige: number;
    op_rookie_title_prestige: number;
    all_modes_rookie_title_prestige: number;
    bridge_rookie_title_prestige: number;
    tournament_rookie_title_prestige: number;
    tnt_games_rookie_title_prestige: number;
    no_debuff_rookie_title_prestige: number;
    combo_rookie_title_prestige: number;
    sumo_rookie_title_prestige: number;
    bow_rookie_title_prestige: number;
    uhc_rookie_title_prestige: number;
    skywars_rookie_title_prestige: number;
    classic_rookie_title_prestige: number;
    op_duel_health_regenerated: number;
    op_duel_damage_dealt: number;
    op_duel_rounds_played: number;
    op_duel_melee_swings: number;
    op_duel_melee_hits: number;
    bowspleef_duel_rounds_played: number;
    bowspleef_duel_bow_shots: number;
    maps_won_on: string[];
    current_winstreak_mode_bowspleef_duel: number;
    current_tnt_games_winstreak: number;
    bowspleef_duel_deaths: number;
    bowspleef_duel_losses: number;
    sw_duels_kit_new3: string;
    sw_duel_blocks_placed: number;
    sw_duel_damage_dealt: number;
    sw_duel_rounds_played: number;
    sw_duel_health_regenerated: number;
    sw_duel_melee_hits: number;
    sw_duel_melee_swings: number;
    sumo_duel_melee_swings: number;
    sumo_duel_rounds_played: number;
    sumo_duel_melee_hits: number;
    bridge_duel_health_regenerated: number;
    bridge_duel_damage_dealt: number;
    bridge_duel_melee_hits: number;
    bridge_duel_blocks_placed: number;
    bridge_duel_melee_swings: number;
    bridge_duel_bow_hits: number;
    bridge_duel_bow_shots: number;
    blitz_duels_kit: string;
    blitz_duel_melee_hits: number;
    blitz_duel_melee_swings: number;
    blitz_duel_rounds_played: number;
    blitz_duel_health_regenerated: number;
    blitz_duel_damage_dealt: number;
    bow_duel_bow_hits: number;
    bow_duel_bow_shots: number;
    bow_duel_health_regenerated: number;
    bow_duel_damage_dealt: number;
    bow_duel_rounds_played: number;
    potion_duel_heal_pots_used: number;
    potion_duel_melee_swings: number;
    potion_duel_rounds_played: number;
    potion_duel_melee_hits: number;
    potion_duel_health_regenerated: number;
    potion_duel_damage_dealt: number;
    heal_pots_used: number;
    current_uhc_winstreak: number;
    current_winstreak_mode_uhc_duel: number;
    uhc_duel_deaths: number;
    uhc_duel_losses: number;
    mw_duels_class: string;
    mw_duel_bow_shots: number;
    mw_duel_blocks_placed: number;
    mw_duel_melee_hits: number;
    mw_duel_rounds_played: number;
    mw_duel_damage_dealt: number;
    mw_duel_melee_swings: number;
    mw_duel_health_regenerated: number;
    mw_duel_bow_hits: number;
    sw_duel_bow_shots: number;
    leaderboardPage_goals: number;
    bridgeMapWins: string[];
    current_winstreak_mode_bridge_four: number;
    current_bridge_winstreak: number;
    bridge_four_rounds_played: number;
    bridge_four_bridge_deaths: number;
    bridge_four_damage_dealt: number;
    bridge_four_bridge_kills: number;
    bridge_four_bow_hits: number;
    bridge_four_blocks_placed: number;
    bridge_four_bow_shots: number;
    bridge_four_losses: number;
    bridge_four_melee_swings: number;
    bridge_four_health_regenerated: number;
    bridge_four_melee_hits: number;
    bridge_kills: number;
    bridge_deaths: number;
    classic_duel_rounds_played: number;
    classic_duel_melee_hits: number;
    classic_duel_health_regenerated: number;
    classic_duel_damage_dealt: number;
    classic_duel_bow_shots: number;
    classic_duel_melee_swings: number;
    current_winstreak_mode_sw_doubles: number;
    sw_doubles_blocks_placed: number;
    current_winstreak_mode_sw_duel: number;
    sw_duel_losses: number;
    sw_duel_deaths: number;
    best_winstreak_mode_sw_duel: number;
    sw_duel_armorer_kit_wins: number;
    sw_duel_kit_wins: number;
    sw_duel_wins: number;
    golden_apples_eaten: number;
    uhc_duel_golden_apples_eaten: number;
    current_winstreak_mode_bridge_duel: number;
    bridge_duel_bridge_deaths: number;
    bridge_duel_bridge_kills: number;
    current_winstreak_mode_bridge_doubles: number;
    bridge_doubles_rounds_played: number;
    bridge_doubles_damage_dealt: number;
    bridge_doubles_health_regenerated: number;
    bridge_doubles_blocks_placed: number;
    bridge_doubles_melee_swings: number;
    bridge_doubles_melee_hits: number;
    bridge_doubles_losses: number;
    sw_duel_bow_hits: number;
    best_winstreak_mode_sw_doubles: number;
    bridge_doubles_bridge_deaths: number;
    bridge_doubles_bridge_kills: number;
    bridge_doubles_bow_shots: number;
    bridge_doubles_bow_hits: number;
    bridge_doubles_goals: number;
    sw_duel_kills: number;
    best_bridge_winstreak: number;
    best_winstreak_mode_bridge_duel: number;
    bridge_duel_wins: number;
    current_winstreak_mode_sumo_duel: number;
    current_sumo_winstreak: number;
    sumo_duel_losses: number;
    sumo_duel_deaths: number;
    classic_duel_bow_hits: number;
    leaderboardPage_win_streak: number;
    current_classic_winstreak: number;
    current_winstreak_mode_classic_duel: number;
    classic_duel_losses: number;
    classic_duel_deaths: number;
    current_blitz_winstreak: number;
    current_winstreak_mode_blitz_duel: number;
    blitz_duel_losses: number;
    blitz_duel_deaths: number;
    pingPreference: number;
    best_uhc_winstreak: number;
    best_winstreak_mode_uhc_duel: number;
    uhc_duel_kills: number;
    uhc_duel_wins: number;
    duels_winstreak_best_uhc_duel: number;
    blitz_duel_blocks_placed: number;
    blitz_duel_bow_shots: number;
    blitz_duel_bow_hits: number;
    combo_duel_melee_hits: number;
    combo_duel_melee_swings: number;
    combo_duel_rounds_played: number;
    combo_duel_health_regenerated: number;
    duels_recently_played2: string;
    best_blitz_winstreak: number;
    best_winstreak_mode_blitz_duel: number;
    pigman_kit_wins: number;
    blitz_duel_kit_wins: number;
    blitz_duel_wins: number;
    blitz_duel_kills: number;
    blitz_duel_pigman_kit_wins: number;
    duels_winstreak_best_blitz_duel: number;
    warlock_kit_wins: number;
    blitz_duel_warlock_kit_wins: number;
    blitz_duel_blaze_kit_wins: number;
    blaze_kit_wins: number;
    blitz_duel_jockey_kit_wins: number;
    jockey_kit_wins: number;
    blitz_duel_baker_kit_wins: number;
    baker_kit_wins: number;
    ranger_kit_wins: number;
    blitz_duel_ranger_kit_wins: number;
    best_classic_winstreak: number;
    best_winstreak_mode_classic_duel: number;
    classic_duel_wins: number;
    classic_duel_kills: number;
    sw_duel_champion_kit_wins: number;
    champion_kit_wins: number;
    duels_winstreak_best_sw_duel: number;
    kit_menu_option: string;
    duels_chests: number;
    best_tnt_games_winstreak: number;
    best_winstreak_mode_bowspleef_duel: number;
    bowspleef_duel_wins: number;
    current_winstreak_mode_uhc_meetup: number;
    uhc_meetup_health_regenerated: number;
    uhc_meetup_bow_shots: number;
    uhc_meetup_losses: number;
    uhc_meetup_deaths: number;
    uhc_meetup_melee_hits: number;
    uhc_meetup_bow_hits: number;
    uhc_meetup_damage_dealt: number;
    uhc_meetup_blocks_placed: number;
    uhc_meetup_rounds_played: number;
    uhc_meetup_melee_swings: number;
    best_winstreak_mode_bridge_four: number;
    bridge_four_wins: number;
    current_combo_winstreak: number;
    current_winstreak_mode_combo_duel: number;
    combo_duel_losses: number;
    combo_duel_deaths: number;
    combo_duel_golden_apples_eaten: number;
    best_winstreak_mode_combo_duel: number;
    best_combo_winstreak: number;
    combo_duel_wins: number;
    combo_duel_kills: number;
    duels_winstreak_best_combo_duel: number;
    packages: string[];
    Duels_openedChests: number;
    duels_chest_history: string[];
    Duels_openedCommons: number;
    Duels_openedRares: number;
    active_kill_effect: string;
    Duels_openedEpics: number;
    active_emblem: string;
    active_killmessages: string;
    active_auras: string;
    active_cosmetictitle: string;
    challenges_enabled: boolean;
    shop_sort: string;
    shop_sort_enable_owned_first: boolean;
    active_projectile_trail: string;
    active_cage: string;
    active_goal: string;
    scout_kit_wins: number;
    sw_duel_scout_kit_wins: number;
    current_winstreak_mode_op_duel: number;
    op_duel_deaths: number;
    op_duel_losses: number;
    best_winstreak_mode_mw_doubles: number;
    current_winstreak_mode_mw_doubles: number;
    best_mega_walls_winstreak: number;
    current_mega_walls_winstreak: number;
    mw_doubles_melee_hits: number;
    mw_doubles_damage_dealt: number;
    mw_doubles_health_regenerated: number;
    mw_doubles_kills: number;
    herobrine_kit_wins: number;
    mw_doubles_wins: number;
    mw_doubles_rounds_played: number;
    mw_doubles_kit_wins: number;
    mw_doubles_herobrine_kit_wins: number;
    mw_doubles_bow_hits: number;
    mw_doubles_bow_shots: number;
    mw_doubles_melee_swings: number;
    current_winstreak_mode_uhc_doubles: number;
    uhc_doubles_losses: number;
    uhc_doubles_bow_shots: number;
    uhc_doubles_rounds_played: number;
    uhc_doubles_melee_swings: number;
    uhc_doubles_health_regenerated: number;
    uhc_doubles_melee_hits: number;
    uhc_doubles_deaths: number;
    uhc_doubles_damage_dealt: number;
    favoriteGlyph: string;
    Duels_openedLegendaries: number;
    active_victory_dance: string;
    active_hat: string;
    best_winstreak_mode_sumo_duel: number;
    best_sumo_winstreak: number;
    sumo_duel_kills: number;
    sumo_duel_wins: number;
    blitz_duel_reddragon_kit_wins: number;
    reddragon_kit_wins: number;
    enderman_a_meters_travelled: number;
    enderman_a_meters_travelled_standard: number;
    enderman_meters_travelled: number;
    enderman_meters_travelled_standard: number;
    meters_travelled: number;
    meters_travelled_standard: number;
    current_winstreak_mode_mw_duel: number;
    mw_duel_deaths: number;
    mw_duel_losses: number;
    blizzard_seconds_slow: number;
    blizzard_seconds_slow_standard: number;
    snowman_blizzard_seconds_slow: number;
    snowman_blizzard_seconds_slow_standard: number;
    arrows_from_rend: number;
    arrows_from_rend_standard: number;
    renegade_arrows_from_rend: number;
    renegade_arrows_from_rend_standard: number;
    duels_showqueuebook: boolean;
    current_winstreak_mode_op_doubles: number;
    op_doubles_deaths: number;
    op_doubles_losses: number;
    current_bow_winstreak: number;
    current_winstreak_mode_bow_duel: number;
    bow_duel_deaths: number;
    bow_duel_losses: number;
    assassin_master_alechmy_hearts: number;
    assassin_master_alechmy_hearts_standard: number;
    assassin_strikes_from_cloak: number;
    assassin_strikes_from_cloak_standard: number;
    master_alechmy_hearts: number;
    master_alechmy_hearts_standard: number;
    strikes_from_cloak: number;
    strikes_from_cloak_standard: number;
    uhc_doubles_blocks_placed: number;
    uhc_doubles_bow_hits: number;
    uhc_doubles_golden_apples_eaten: number;
    amount_healed: number;
    amount_healed_standard: number;
    blaze_amount_healed: number;
    blaze_amount_healed_standard: number;
    blaze_g_amount_healed: number;
    blaze_g_amount_healed_standard: number;
    best_winstreak_mode_bridge_doubles: number;
    bridge_doubles_wins: number;
    uhc_meetup_kills: number;
    best_winstreak_mode_bow_duel: number;
    best_bow_winstreak: number;
    bow_duel_kills: number;
    bow_duel_wins: number;
    duels_winstreak_best_bridge_duel: number;
    active_weaponpacks: string;
    duels_winstreak_best_bridge_doubles: number;
    duels_winstreak_best_null: number;
    best_winstreak_mode_bridge_3v3v3v3: number;
    current_winstreak_mode_bridge_3v3v3v3: number;
    bridge_3v3v3v3_blocks_placed: number;
    bridge_3v3v3v3_bow_hits: number;
    bridge_3v3v3v3_bow_shots: number;
    bridge_3v3v3v3_bridge_deaths: number;
    bridge_3v3v3v3_bridge_kills: number;
    bridge_3v3v3v3_damage_dealt: number;
    bridge_3v3v3v3_goals: number;
    bridge_3v3v3v3_health_regenerated: number;
    bridge_3v3v3v3_melee_hits: number;
    bridge_3v3v3v3_melee_swings: number;
    bridge_3v3v3v3_rounds_played: number;
    bridge_3v3v3v3_wins: number;
    leaderboardPage_wins: number;
    frog_kit_wins: number;
    sw_duel_frog_kit_wins: number;
    bridge_3v3v3v3_losses: number;
    energy_from_grappling_hook: number;
    energy_from_grappling_hook_standard: number;
    renegade_energy_from_grappling_hook: number;
    renegade_energy_from_grappling_hook_standard: number;
    best_winstreak_mode_mw_duel: number;
    mw_duel_kills: number;
    mw_duel_kit_wins: number;
    mw_duel_phoenix_kit_wins: number;
    mw_duel_wins: number;
    phoenix_kit_wins: number;
    bucket_barriers_broken: number;
    bucket_barriers_broken_standard: number;
    cow_bucket_barriers_broken: number;
    cow_bucket_barriers_broken_standard: number;
    blitz_duel_rogue_kit_wins: number;
    rogue_kit_wins: number;
    duels_winstreak_best_classic_duel: number;
    best_winstreak_mode_op_duel: number;
    op_duel_kills: number;
    op_duel_wins: number;
    all_modes_iron_title_prestige: number;
    duels_winstreak_best_sumo_duel: number;
    sw_doubles_scout_kit_wins: number;
  }

  export interface GingerBread {
    frame_active: string;
    packages: string[];
    booster_active: string;
    engine_active: string;
    shoes_active: string;
    jacket_active: string;
    skin_active: string;
    pants_active: string;
    helmet_active: string;
    horn: string;
    coins: number;
    banana_hits_sent: number;
    banana_hits_received: number;
    box_pickups: number;
    coins_picked_up: number;
    canyon_plays: number;
    laps_completed: number;
    hypixelgp_plays: number;
    bronze_trophy: number;
    wins: number;
    parts: string;
    lastTourneyAd: number;
    blue_torpedo_hit: number;
    box_pickups_retro: number;
    retro_plays: number;
    box_pickups_olympus: number;
    olympus_plays: number;
  }

  export interface VanityMeta {
    packages: string[];
  }

  export interface HungerGames {
    deaths: number;
    coins: number;
    packages: string[];
    chests_opened: number;
    damage: number;
    time_played: number;
    games_played: number;
    wins_backup: number;
    autoarmor: boolean;
    wins_teams_normal: number;
    wins: number;
    wins_solo_normal: number;
    lastTourneyAd: number;
    potions_thrown: number;
    potions_drunk: number;
    arrows_fired: number;
    kills: number;
    arrows_hit: number;
    afterkill: string;
    mobs_spawned: number;
    random_wins: number;
    wins_teams: number;
    reaper: number;
    blitz_uses: number;
    prefers_full_kits_menu: boolean;
  }

  export interface Legacy {
    next_tokens_seconds: number;
    paintball_tokens: number;
    total_tokens: number;
    tokens: number;
    arena_tokens: number;
    vampirez_tokens: number;
    quakecraft_tokens: number;
    walls_tokens: number;
    preferredChannel: string;
    gingerbread_tokens: number;
  }

  export interface Mcgo {
    deaths: number;
    shots_fired: number;
    coins: number;
    headshot_kills: number;
    packages: string[];
    mcgo: McgoClass;
    deaths_deathmatch: number;
    cop_kills_deathmatch: number;
    weekly_kills_a: number;
    kills_deathmatch: number;
    monthly_kills_b: number;
    kills: number;
    criminal_kills: number;
    game_wins: number;
    round_wins: number;
    pocket_change: number;
    game_wins_deathmatch: number;
    grenadeKills: number;
    bombs_planted: number;
    bombs_defused: number;
    grenade_kills: number;
    cop_kills: number;
    game_wins_alleyway: number;
    game_wins_reserve: number;
    selectedKnifeDev: string;
    selectedRifleDev: string;
    selectedShotgunDev: string;
    selectedSmgDev: string;
    setting_animated_smoke: boolean;
    show_lobby_prefix: boolean;
    selected_lobby_prefix: string;
    lastTourneyAd: number;
    cop_kills_tourney_mcgo_defusal_0: number;
    criminal_kills_tourney_mcgo_defusal_0: number;
    game_plays_tourney_mcgo_defusal_0: number;
    game_wins_atomic: number;
    game_wins_tourney_mcgo_defusal_0: number;
    headshot_kills_tourney_mcgo_defusal_0: number;
    kills_tourney_mcgo_defusal_0: number;
    round_wins_tourney_mcgo_defusal_0: number;
    shots_fired_tourney_mcgo_defusal_0: number;
    bombs_planted_tourney_mcgo_defusal_0: number;
    deaths_tourney_mcgo_defusal_0: number;
    bombs_defused_tourney_mcgo_defusal_0: number;
    game_wins_carrier: number;
    game_wins_sandstorm: number;
    strength_training: number;
    bounty_hunter: number;
    smg_reload_speed_reduction: number;
    smg_cost_reduction: number;
    smg_recoil_reduction: number;
    smg_damage_increase: number;
    pistol_damage_increase: number;
    pistol_recoil_reduction: number;
    selectedPistolDev: string;
    pistol_reload_speed_reduction: number;
    knife_attack_delay: number;
    knife_damage_increase: number;
    body_armor_cost: number;
    selectedOcelotHelmetDev: string;
    selectedOcelotChestplateDev: string;
    selectedCreeperChestplateDev: string;
    selectedCreeperHelmetDev: string;
    selectedCarbineDev: string;
    selectedMagnumDev: string;
    shotgun_reload_speed_reduction: number;
    shotgun_recoil_reduction: number;
    shotgun_damage_increase: number;
    game_wins_overgrown: number;
    rifle_reload_speed_reduction: number;
    rifle_cost_reduction: number;
    rifle_recoil_reduction: number;
    rifle_damage_increase: number;
  }

  export interface McgoClass {
    points: number;
  }

  export interface Paintball {
    packages: string[];
    favorite_slots: string;
    kills: number;
    shots_fired: number;
    coins: number;
    deaths: number;
    wins: number;
    showKillPrefix: boolean;
  }

  export interface Pit {
    profile: PitProfile;
    pit_stats_ptl: { [key: string]: number };
    stats_move_1: number;
  }

  export interface PitProfile {
    renown: number;
    moved_achievements_1: boolean;
    outgoing_offers: any[];
    moved_achievements_2: boolean;
    contract_choices: null;
    last_save: number;
    king_quest: KingQuest;
    prestiges: Prestige[];
    chat_option_misc: boolean;
    spire_stash_inv: DeathRecaps;
    cheap_milk: boolean;
    zero_point_three_gold_transfer: boolean;
    unlocks_1: RenownUnlock[];
    renown_unlocks: RenownUnlock[];
    death_recaps: DeathRecaps;
    inv_enderchest: DeathRecaps;
    spire_stash_armor: DeathRecaps;
    cash: number;
    last_midfight_disconnect: number;
    leaderboard_stats: { [key: string]: number };
    selected_perk_3: null;
    selected_perk_2: string;
    inv_armor: DeathRecaps;
    selected_perk_1: string;
    selected_perk_0: string;
    last_contract: number;
    item_stash: DeathRecaps;
    selected_killstreak_2: string;
    selected_killstreak_1: string;
    login_messages: any[];
    hotbar_favorites: number[];
    xp: number;
    inv_contents: DeathRecaps;
    ended_contracts: EndedContract[];
    bounties: any[];
    unlocks: RenownUnlock[];
    cash_during_prestige_1: number;
    cash_during_prestige_0: number;
  }

  export interface DeathRecaps {
    type: number;
    data: number[];
  }

  export interface EndedContract {
    difficulty: string;
    gold_reward: number;
    requirements: Progress;
    progress: Progress;
    chunk_of_viles_reward: number;
    completion_date: number;
    remaining_ticks: number;
    key: string;
  }

  export interface Progress {
    ingots: number;
  }

  export interface KingQuest {
    kills: number;
    renown: number;
    last_accepted: number;
  }

  export interface Prestige {
    index: number;
    xp_on_prestige: number;
    timestamp: number;
  }

  export interface RenownUnlock {
    tier: number;
    acquireDate: number;
    key: string;
  }

  export interface Quake {
    packages: string[];
    kills: number;
    coins: number;
    monthly_kills_b: number;
    weekly_kills_b: number;
    deaths: number;
    instantRespawn: boolean;
    enable_sound: boolean;
    alternative_gun_cooldown_indicator: boolean;
    compass_selected: boolean;
    'messageYour Deaths': boolean;
    "messageOthers' Kills/deaths": boolean;
    'messageYour Kills': boolean;
    highest_killstreak: number;
    'messageCoin Messages': boolean;
    showDashCooldown: boolean;
    'messageMulti-kills': boolean;
    messageKillstreaks: boolean;
    distance_travelled: number;
    shots_fired: number;
    kills_since_update_feb_2017: number;
    kills_teams: number;
    kills_timeattack: number;
    showKillPrefix: boolean;
    kills_dm: number;
    kills_dm_teams: number;
    headshots: number;
    'messagePowerup Collections': boolean;
    dash_cooldown: string;
    trigger: string;
    beam: string;
    barrel: string;
    killsound: string;
    muzzle: string;
    killstreaks: number;
    messageCoin: boolean;
    distance_travelled_teams: number;
    kills_since_update_feb_2017_teams: number;
    shots_fired_teams: number;
    deaths_teams: number;
    headshots_teams: number;
    kills_solo_tourney: number;
    case: string;
  }

  export interface Bedwars {
    _items_purchased_bedwars: number;
    activeBedDestroy: string;
    activeDeathCry: string;
    activeGlyph: string;
    activeIslandTopper: string;
    activeKillEffect: string;
    activeKillMessages: string;
    activeNPCSkin: string;
    activeProjectileTrail: string;
    activeSprays: string;
    activeVictoryDance: string;
    activeWoodType: string;
    beds_broken_bedwars: number;
    beds_lost_bedwars: number;
    Bedwars_openedChests: number;
    Bedwars_openedCommons: number;
    Bedwars_openedEpics: number;
    Bedwars_openedRares: number;
    Bedwars_openedLegendaries: number;
    castle__items_purchased_bedwars: number;
    castle_beds_lost_bedwars: number;
    castle_deaths_bedwars: number;
    castle_diamond_resources_collected_bedwars: number;
    castle_emerald_resources_collected_bedwars: number;
    castle_entity_attack_deaths_bedwars: number;
    castle_entity_attack_final_deaths_bedwars: number;
    castle_entity_attack_final_kills_bedwars: number;
    castle_entity_attack_kills_bedwars: number;
    castle_entity_explosion_deaths_bedwars: number;
    castle_entity_explosion_final_kills_bedwars: number;
    castle_entity_explosion_kills_bedwars: number;
    castle_fall_deaths_bedwars: number;
    castle_fall_final_kills_bedwars: number;
    castle_fall_kills_bedwars: number;
    castle_final_deaths_bedwars: number;
    castle_final_kills_bedwars: number;
    castle_games_played_bedwars: number;
    castle_gold_resources_collected_bedwars: number;
    castle_iron_resources_collected_bedwars: number;
    castle_items_purchased_bedwars: number;
    castle_kills_bedwars: number;
    castle_losses_bedwars: number;
    'castle_permanent _items_purchased_bedwars': number;
    castle_permanent_items_purchased_bedwars: number;
    castle_resources_collected_bedwars: number;
    castle_void_deaths_bedwars: number;
    castle_void_final_kills_bedwars: number;
    castle_void_kills_bedwars: number;
    castle_wins_bedwars: number;
    castle_winstreak: number;
    coins: number;
    deaths_bedwars: number;
    diamond_resources_collected_bedwars: number;
    eight_one__items_purchased_bedwars: number;
    eight_one_beds_broken_bedwars: number;
    eight_one_beds_lost_bedwars: number;
    eight_one_deaths_bedwars: number;
    eight_one_diamond_resources_collected_bedwars: number;
    eight_one_emerald_resources_collected_bedwars: number;
    eight_one_entity_attack_deaths_bedwars: number;
    eight_one_entity_attack_final_deaths_bedwars: number;
    eight_one_entity_attack_final_kills_bedwars: number;
    eight_one_entity_attack_kills_bedwars: number;
    eight_one_entity_explosion_deaths_bedwars: number;
    eight_one_entity_explosion_final_deaths_bedwars: number;
    eight_one_entity_explosion_final_kills_bedwars: number;
    eight_one_fall_deaths_bedwars: number;
    eight_one_fall_final_deaths_bedwars: number;
    eight_one_fall_final_kills_bedwars: number;
    eight_one_fall_kills_bedwars: number;
    eight_one_final_deaths_bedwars: number;
    eight_one_final_kills_bedwars: number;
    eight_one_games_played_bedwars: number;
    eight_one_gold_resources_collected_bedwars: number;
    eight_one_iron_resources_collected_bedwars: number;
    eight_one_items_purchased_bedwars: number;
    eight_one_kills_bedwars: number;
    eight_one_losses_bedwars: number;
    eight_one_magic_deaths_bedwars: number;
    eight_one_magic_final_deaths_bedwars: number;
    eight_one_magic_final_kills_bedwars: number;
    'eight_one_permanent _items_purchased_bedwars': number;
    eight_one_permanent_items_purchased_bedwars: number;
    eight_one_resources_collected_bedwars: number;
    eight_one_suffocation_deaths_bedwars: number;
    eight_one_void_deaths_bedwars: number;
    eight_one_void_final_deaths_bedwars: number;
    eight_one_void_final_kills_bedwars: number;
    eight_one_void_kills_bedwars: number;
    eight_one_wins_bedwars: number;
    eight_one_winstreak: number;
    eight_two__items_purchased_bedwars: number;
    eight_two_armed__items_purchased_bedwars: number;
    eight_two_armed_beds_broken_bedwars: number;
    eight_two_armed_beds_lost_bedwars: number;
    eight_two_armed_deaths_bedwars: number;
    eight_two_armed_diamond_resources_collected_bedwars: number;
    eight_two_armed_emerald_resources_collected_bedwars: number;
    eight_two_armed_entity_attack_deaths_bedwars: number;
    eight_two_armed_entity_attack_final_deaths_bedwars: number;
    eight_two_armed_entity_attack_kills_bedwars: number;
    eight_two_armed_entity_explosion_deaths_bedwars: number;
    eight_two_armed_entity_explosion_final_kills_bedwars: number;
    eight_two_armed_fall_deaths_bedwars: number;
    eight_two_armed_fall_final_deaths_bedwars: number;
    eight_two_armed_final_deaths_bedwars: number;
    eight_two_armed_final_kills_bedwars: number;
    eight_two_armed_games_played_bedwars: number;
    eight_two_armed_gold_resources_collected_bedwars: number;
    eight_two_armed_iron_resources_collected_bedwars: number;
    eight_two_armed_items_purchased_bedwars: number;
    eight_two_armed_kills_bedwars: number;
    eight_two_armed_losses_bedwars: number;
    eight_two_armed_magic_final_deaths_bedwars: number;
    'eight_two_armed_permanent _items_purchased_bedwars': number;
    eight_two_armed_projectile_deaths_bedwars: number;
    eight_two_armed_projectile_final_deaths_bedwars: number;
    eight_two_armed_projectile_final_kills_bedwars: number;
    eight_two_armed_projectile_kills_bedwars: number;
    eight_two_armed_resources_collected_bedwars: number;
    eight_two_armed_void_deaths_bedwars: number;
    eight_two_armed_void_final_kills_bedwars: number;
    eight_two_armed_void_kills_bedwars: number;
    eight_two_armed_winstreak: number;
    eight_two_beds_broken_bedwars: number;
    eight_two_beds_lost_bedwars: number;
    eight_two_deaths_bedwars: number;
    eight_two_diamond_resources_collected_bedwars: number;
    eight_two_emerald_resources_collected_bedwars: number;
    eight_two_entity_attack_deaths_bedwars: number;
    eight_two_entity_attack_final_deaths_bedwars: number;
    eight_two_entity_attack_final_kills_bedwars: number;
    eight_two_entity_attack_kills_bedwars: number;
    eight_two_entity_explosion_deaths_bedwars: number;
    eight_two_entity_explosion_final_deaths_bedwars: number;
    eight_two_entity_explosion_final_kills_bedwars: number;
    eight_two_entity_explosion_kills_bedwars: number;
    eight_two_fall_deaths_bedwars: number;
    eight_two_fall_final_deaths_bedwars: number;
    eight_two_fall_final_kills_bedwars: number;
    eight_two_fall_kills_bedwars: number;
    eight_two_final_deaths_bedwars: number;
    eight_two_final_kills_bedwars: number;
    eight_two_games_played_bedwars: number;
    eight_two_gold_resources_collected_bedwars: number;
    eight_two_iron_resources_collected_bedwars: number;
    eight_two_items_purchased_bedwars: number;
    eight_two_kills_bedwars: number;
    eight_two_losses_bedwars: number;
    eight_two_lucky__items_purchased_bedwars: number;
    eight_two_lucky_beds_broken_bedwars: number;
    eight_two_lucky_beds_lost_bedwars: number;
    eight_two_lucky_deaths_bedwars: number;
    eight_two_lucky_diamond_resources_collected_bedwars: number;
    eight_two_lucky_emerald_resources_collected_bedwars: number;
    eight_two_lucky_entity_attack_deaths_bedwars: number;
    eight_two_lucky_entity_attack_final_deaths_bedwars: number;
    eight_two_lucky_entity_attack_final_kills_bedwars: number;
    eight_two_lucky_entity_attack_kills_bedwars: number;
    eight_two_lucky_entity_explosion_final_kills_bedwars: number;
    eight_two_lucky_final_deaths_bedwars: number;
    eight_two_lucky_final_kills_bedwars: number;
    eight_two_lucky_fire_tick_deaths_bedwars: number;
    eight_two_lucky_fire_tick_final_deaths_bedwars: number;
    eight_two_lucky_fire_tick_final_kills_bedwars: number;
    eight_two_lucky_fire_tick_kills_bedwars: number;
    eight_two_lucky_games_played_bedwars: number;
    eight_two_lucky_gold_resources_collected_bedwars: number;
    eight_two_lucky_iron_resources_collected_bedwars: number;
    eight_two_lucky_items_purchased_bedwars: number;
    eight_two_lucky_kills_bedwars: number;
    eight_two_lucky_lava_kills_bedwars: number;
    eight_two_lucky_losses_bedwars: number;
    eight_two_lucky_magic_final_deaths_bedwars: number;
    'eight_two_lucky_permanent _items_purchased_bedwars': number;
    eight_two_lucky_resources_collected_bedwars: number;
    eight_two_lucky_void_deaths_bedwars: number;
    eight_two_lucky_void_final_deaths_bedwars: number;
    eight_two_lucky_void_final_kills_bedwars: number;
    eight_two_lucky_void_kills_bedwars: number;
    eight_two_lucky_wins_bedwars: number;
    eight_two_lucky_winstreak: number;
    eight_two_magic_deaths_bedwars: number;
    eight_two_magic_final_deaths_bedwars: number;
    eight_two_magic_final_kills_bedwars: number;
    eight_two_magic_kills_bedwars: number;
    'eight_two_permanent _items_purchased_bedwars': number;
    eight_two_permanent_items_purchased_bedwars: number;
    eight_two_resources_collected_bedwars: number;
    eight_two_rush__items_purchased_bedwars: number;
    eight_two_rush_beds_broken_bedwars: number;
    eight_two_rush_beds_lost_bedwars: number;
    eight_two_rush_deaths_bedwars: number;
    eight_two_rush_diamond_resources_collected_bedwars: number;
    eight_two_rush_emerald_resources_collected_bedwars: number;
    eight_two_rush_entity_attack_deaths_bedwars: number;
    eight_two_rush_entity_attack_final_deaths_bedwars: number;
    eight_two_rush_entity_attack_final_kills_bedwars: number;
    eight_two_rush_entity_attack_kills_bedwars: number;
    eight_two_rush_final_deaths_bedwars: number;
    eight_two_rush_final_kills_bedwars: number;
    eight_two_rush_games_played_bedwars: number;
    eight_two_rush_gold_resources_collected_bedwars: number;
    eight_two_rush_iron_resources_collected_bedwars: number;
    eight_two_rush_items_purchased_bedwars: number;
    eight_two_rush_kills_bedwars: number;
    eight_two_rush_losses_bedwars: number;
    'eight_two_rush_permanent _items_purchased_bedwars': number;
    eight_two_rush_resources_collected_bedwars: number;
    eight_two_rush_void_deaths_bedwars: number;
    eight_two_rush_void_final_deaths_bedwars: number;
    eight_two_rush_void_final_kills_bedwars: number;
    eight_two_rush_void_kills_bedwars: number;
    eight_two_rush_wins_bedwars: number;
    eight_two_rush_winstreak: number;
    eight_two_ultimate__items_purchased_bedwars: number;
    eight_two_ultimate_beds_lost_bedwars: number;
    eight_two_ultimate_deaths_bedwars: number;
    eight_two_ultimate_entity_attack_deaths_bedwars: number;
    eight_two_ultimate_entity_attack_final_deaths_bedwars: number;
    eight_two_ultimate_entity_attack_kills_bedwars: number;
    eight_two_ultimate_final_deaths_bedwars: number;
    eight_two_ultimate_final_kills_bedwars: number;
    eight_two_ultimate_games_played_bedwars: number;
    eight_two_ultimate_gold_resources_collected_bedwars: number;
    eight_two_ultimate_iron_resources_collected_bedwars: number;
    eight_two_ultimate_items_purchased_bedwars: number;
    eight_two_ultimate_kills_bedwars: number;
    eight_two_ultimate_losses_bedwars: number;
    eight_two_ultimate_permanent_items_purchased_bedwars: number;
    eight_two_ultimate_resources_collected_bedwars: number;
    eight_two_ultimate_void_deaths_bedwars: number;
    eight_two_ultimate_void_final_deaths_bedwars: number;
    eight_two_ultimate_void_final_kills_bedwars: number;
    eight_two_ultimate_winstreak: number;
    eight_two_void_deaths_bedwars: number;
    eight_two_void_final_deaths_bedwars: number;
    eight_two_void_final_kills_bedwars: number;
    eight_two_void_kills_bedwars: number;
    eight_two_voidless__items_purchased_bedwars: number;
    eight_two_voidless_beds_broken_bedwars: number;
    eight_two_voidless_beds_lost_bedwars: number;
    eight_two_voidless_deaths_bedwars: number;
    eight_two_voidless_diamond_resources_collected_bedwars: number;
    eight_two_voidless_emerald_resources_collected_bedwars: number;
    eight_two_voidless_entity_attack_deaths_bedwars: number;
    eight_two_voidless_entity_attack_final_deaths_bedwars: number;
    eight_two_voidless_entity_attack_final_kills_bedwars: number;
    eight_two_voidless_entity_attack_kills_bedwars: number;
    eight_two_voidless_entity_explosion_kills_bedwars: number;
    eight_two_voidless_fall_deaths_bedwars: number;
    eight_two_voidless_fall_kills_bedwars: number;
    eight_two_voidless_final_deaths_bedwars: number;
    eight_two_voidless_final_kills_bedwars: number;
    eight_two_voidless_games_played_bedwars: number;
    eight_two_voidless_gold_resources_collected_bedwars: number;
    eight_two_voidless_iron_resources_collected_bedwars: number;
    eight_two_voidless_items_purchased_bedwars: number;
    eight_two_voidless_kills_bedwars: number;
    eight_two_voidless_losses_bedwars: number;
    'eight_two_voidless_permanent _items_purchased_bedwars': number;
    eight_two_voidless_resources_collected_bedwars: number;
    eight_two_voidless_wins_bedwars: number;
    eight_two_voidless_winstreak: number;
    eight_two_wins_bedwars: number;
    eight_two_winstreak: number;
    emerald_resources_collected_bedwars: number;
    entity_attack_deaths_bedwars: number;
    entity_attack_final_deaths_bedwars: number;
    entity_attack_final_kills_bedwars: number;
    entity_attack_kills_bedwars: number;
    entity_explosion_deaths_bedwars: number;
    entity_explosion_final_deaths_bedwars: number;
    entity_explosion_final_kills_bedwars: number;
    entity_explosion_kills_bedwars: number;
    Experience: number;
    fall_deaths_bedwars: number;
    fall_final_deaths_bedwars: number;
    fall_final_kills_bedwars: number;
    fall_kills_bedwars: number;
    final_deaths_bedwars: number;
    final_kills_bedwars: number;
    fire_deaths_bedwars: number;
    fire_tick_deaths_bedwars: number;
    first_join_7: true;
    four_four__items_purchased_bedwars: number;
    four_four_armed__items_purchased_bedwars: number;
    four_four_armed_beds_lost_bedwars: number;
    four_four_armed_deaths_bedwars: number;
    four_four_armed_diamond_resources_collected_bedwars: number;
    four_four_armed_emerald_resources_collected_bedwars: number;
    four_four_armed_entity_attack_deaths_bedwars: number;
    four_four_armed_entity_attack_final_kills_bedwars: number;
    four_four_armed_entity_attack_kills_bedwars: number;
    four_four_armed_fall_deaths_bedwars: number;
    four_four_armed_final_deaths_bedwars: number;
    four_four_armed_final_kills_bedwars: number;
    four_four_armed_games_played_bedwars: number;
    four_four_armed_gold_resources_collected_bedwars: number;
    four_four_armed_iron_resources_collected_bedwars: number;
    four_four_armed_items_purchased_bedwars: number;
    four_four_armed_kills_bedwars: number;
    four_four_armed_losses_bedwars: number;
    'four_four_armed_permanent _items_purchased_bedwars': number;
    four_four_armed_permanent_items_purchased_bedwars: number;
    four_four_armed_projectile_deaths_bedwars: number;
    four_four_armed_projectile_final_deaths_bedwars: number;
    four_four_armed_projectile_kills_bedwars: number;
    four_four_armed_resources_collected_bedwars: number;
    four_four_armed_void_deaths_bedwars: number;
    four_four_armed_void_kills_bedwars: number;
    four_four_armed_wins_bedwars: number;
    four_four_armed_winstreak: number;
    four_four_beds_broken_bedwars: number;
    four_four_beds_lost_bedwars: number;
    four_four_deaths_bedwars: number;
    four_four_diamond_resources_collected_bedwars: number;
    four_four_emerald_resources_collected_bedwars: number;
    four_four_entity_attack_deaths_bedwars: number;
    four_four_entity_attack_final_deaths_bedwars: number;
    four_four_entity_attack_final_kills_bedwars: number;
    four_four_entity_attack_kills_bedwars: number;
    four_four_entity_explosion_deaths_bedwars: number;
    four_four_entity_explosion_final_kills_bedwars: number;
    four_four_entity_explosion_kills_bedwars: number;
    four_four_fall_deaths_bedwars: number;
    four_four_fall_final_deaths_bedwars: number;
    four_four_fall_final_kills_bedwars: number;
    four_four_fall_kills_bedwars: number;
    four_four_final_deaths_bedwars: number;
    four_four_final_kills_bedwars: number;
    four_four_games_played_bedwars: number;
    four_four_gold_resources_collected_bedwars: number;
    four_four_iron_resources_collected_bedwars: number;
    four_four_items_purchased_bedwars: number;
    four_four_kills_bedwars: number;
    four_four_losses_bedwars: number;
    four_four_lucky__items_purchased_bedwars: number;
    four_four_lucky_beds_broken_bedwars: number;
    four_four_lucky_beds_lost_bedwars: number;
    four_four_lucky_deaths_bedwars: number;
    four_four_lucky_diamond_resources_collected_bedwars: number;
    four_four_lucky_emerald_resources_collected_bedwars: number;
    four_four_lucky_entity_attack_deaths_bedwars: number;
    four_four_lucky_entity_attack_final_deaths_bedwars: number;
    four_four_lucky_entity_attack_final_kills_bedwars: number;
    four_four_lucky_entity_attack_kills_bedwars: number;
    four_four_lucky_final_deaths_bedwars: number;
    four_four_lucky_final_kills_bedwars: number;
    four_four_lucky_games_played_bedwars: number;
    four_four_lucky_gold_resources_collected_bedwars: number;
    four_four_lucky_iron_resources_collected_bedwars: number;
    four_four_lucky_items_purchased_bedwars: number;
    four_four_lucky_kills_bedwars: number;
    four_four_lucky_losses_bedwars: number;
    four_four_lucky_magic_final_deaths_bedwars: number;
    four_four_lucky_magic_kills_bedwars: number;
    'four_four_lucky_permanent _items_purchased_bedwars': number;
    four_four_lucky_permanent_items_purchased_bedwars: number;
    four_four_lucky_resources_collected_bedwars: number;
    four_four_lucky_void_deaths_bedwars: number;
    four_four_lucky_void_final_deaths_bedwars: number;
    four_four_lucky_void_final_kills_bedwars: number;
    four_four_lucky_void_kills_bedwars: number;
    four_four_lucky_wins_bedwars: number;
    four_four_lucky_winstreak: number;
    four_four_magic_final_deaths_bedwars: number;
    four_four_magic_final_kills_bedwars: number;
    four_four_magic_kills_bedwars: number;
    'four_four_permanent _items_purchased_bedwars': number;
    four_four_permanent_items_purchased_bedwars: number;
    four_four_resources_collected_bedwars: number;
    four_four_rush__items_purchased_bedwars: number;
    four_four_rush_beds_broken_bedwars: number;
    four_four_rush_beds_lost_bedwars: number;
    four_four_rush_deaths_bedwars: number;
    four_four_rush_diamond_resources_collected_bedwars: number;
    four_four_rush_emerald_resources_collected_bedwars: number;
    four_four_rush_entity_attack_deaths_bedwars: number;
    four_four_rush_entity_attack_final_deaths_bedwars: number;
    four_four_rush_entity_attack_final_kills_bedwars: number;
    four_four_rush_entity_attack_kills_bedwars: number;
    four_four_rush_final_deaths_bedwars: number;
    four_four_rush_final_kills_bedwars: number;
    four_four_rush_games_played_bedwars: number;
    four_four_rush_gold_resources_collected_bedwars: number;
    four_four_rush_iron_resources_collected_bedwars: number;
    four_four_rush_items_purchased_bedwars: number;
    four_four_rush_kills_bedwars: number;
    four_four_rush_losses_bedwars: number;
    'four_four_rush_permanent _items_purchased_bedwars': number;
    four_four_rush_permanent_items_purchased_bedwars: number;
    four_four_rush_resources_collected_bedwars: number;
    four_four_rush_suffocation_deaths_bedwars: number;
    four_four_rush_void_deaths_bedwars: number;
    four_four_rush_void_final_deaths_bedwars: number;
    four_four_rush_void_final_kills_bedwars: number;
    four_four_rush_void_kills_bedwars: number;
    four_four_rush_wins_bedwars: number;
    four_four_rush_winstreak: number;
    four_four_ultimate__items_purchased_bedwars: number;
    four_four_ultimate_beds_broken_bedwars: number;
    four_four_ultimate_beds_lost_bedwars: number;
    four_four_ultimate_deaths_bedwars: number;
    four_four_ultimate_diamond_resources_collected_bedwars: number;
    four_four_ultimate_emerald_resources_collected_bedwars: number;
    four_four_ultimate_entity_attack_deaths_bedwars: number;
    four_four_ultimate_entity_attack_final_deaths_bedwars: number;
    four_four_ultimate_entity_attack_final_kills_bedwars: number;
    four_four_ultimate_entity_attack_kills_bedwars: number;
    four_four_ultimate_final_deaths_bedwars: number;
    four_four_ultimate_final_kills_bedwars: number;
    four_four_ultimate_games_played_bedwars: number;
    four_four_ultimate_gold_resources_collected_bedwars: number;
    four_four_ultimate_iron_resources_collected_bedwars: number;
    four_four_ultimate_items_purchased_bedwars: number;
    four_four_ultimate_kills_bedwars: number;
    four_four_ultimate_losses_bedwars: number;
    'four_four_ultimate_permanent _items_purchased_bedwars': number;
    four_four_ultimate_resources_collected_bedwars: number;
    four_four_ultimate_void_deaths_bedwars: number;
    four_four_ultimate_void_final_deaths_bedwars: number;
    four_four_ultimate_void_final_kills_bedwars: number;
    four_four_ultimate_void_kills_bedwars: number;
    four_four_ultimate_wins_bedwars: number;
    four_four_ultimate_winstreak: number;
    four_four_void_deaths_bedwars: number;
    four_four_void_final_deaths_bedwars: number;
    four_four_void_final_kills_bedwars: number;
    four_four_void_kills_bedwars: number;
    four_four_voidless__items_purchased_bedwars: number;
    four_four_voidless_beds_broken_bedwars: number;
    four_four_voidless_beds_lost_bedwars: number;
    four_four_voidless_deaths_bedwars: number;
    four_four_voidless_diamond_resources_collected_bedwars: number;
    four_four_voidless_entity_attack_deaths_bedwars: number;
    four_four_voidless_entity_attack_final_deaths_bedwars: number;
    four_four_voidless_entity_attack_final_kills_bedwars: number;
    four_four_voidless_entity_attack_kills_bedwars: number;
    four_four_voidless_entity_explosion_final_kills_bedwars: number;
    four_four_voidless_fall_final_deaths_bedwars: number;
    four_four_voidless_final_deaths_bedwars: number;
    four_four_voidless_final_kills_bedwars: number;
    four_four_voidless_games_played_bedwars: number;
    four_four_voidless_gold_resources_collected_bedwars: number;
    four_four_voidless_iron_resources_collected_bedwars: number;
    four_four_voidless_items_purchased_bedwars: number;
    four_four_voidless_kills_bedwars: number;
    four_four_voidless_losses_bedwars: number;
    'four_four_voidless_permanent _items_purchased_bedwars': number;
    four_four_voidless_permanent_items_purchased_bedwars: number;
    four_four_voidless_resources_collected_bedwars: number;
    four_four_voidless_void_final_deaths_bedwars: number;
    four_four_voidless_wins_bedwars: number;
    four_four_voidless_winstreak: number;
    four_four_wins_bedwars: number;
    four_four_winstreak: number;
    four_three__items_purchased_bedwars: number;
    four_three_beds_broken_bedwars: number;
    four_three_beds_lost_bedwars: number;
    four_three_deaths_bedwars: number;
    four_three_diamond_resources_collected_bedwars: number;
    four_three_emerald_resources_collected_bedwars: number;
    four_three_entity_attack_deaths_bedwars: number;
    four_three_entity_attack_final_deaths_bedwars: number;
    four_three_entity_attack_final_kills_bedwars: number;
    four_three_entity_attack_kills_bedwars: number;
    four_three_entity_explosion_deaths_bedwars: number;
    four_three_entity_explosion_kills_bedwars: number;
    four_three_fall_deaths_bedwars: number;
    four_three_fall_final_deaths_bedwars: number;
    four_three_fall_final_kills_bedwars: number;
    four_three_fall_kills_bedwars: number;
    four_three_final_deaths_bedwars: number;
    four_three_final_kills_bedwars: number;
    four_three_fire_deaths_bedwars: number;
    four_three_fire_tick_deaths_bedwars: number;
    four_three_games_played_bedwars: number;
    four_three_gold_resources_collected_bedwars: number;
    four_three_iron_resources_collected_bedwars: number;
    four_three_items_purchased_bedwars: number;
    four_three_kills_bedwars: number;
    four_three_losses_bedwars: number;
    four_three_magic_deaths_bedwars: number;
    four_three_magic_final_deaths_bedwars: number;
    four_three_magic_final_kills_bedwars: number;
    four_three_magic_kills_bedwars: number;
    'four_three_permanent _items_purchased_bedwars': number;
    four_three_permanent_items_purchased_bedwars: number;
    four_three_projectile_deaths_bedwars: number;
    four_three_resources_collected_bedwars: number;
    four_three_void_deaths_bedwars: number;
    four_three_void_final_deaths_bedwars: number;
    four_three_void_final_kills_bedwars: number;
    four_three_void_kills_bedwars: number;
    four_three_wins_bedwars: number;
    four_three_winstreak: number;
    games_played_bedwars_1: number;
    games_played_bedwars: number;
    gold_resources_collected_bedwars: number;
    iron_resources_collected_bedwars: number;
    items_purchased_bedwars: number;
    kills_bedwars: number;
    losses_bedwars: number;
    magic_deaths_bedwars: number;
    magic_final_deaths_bedwars: number;
    magic_final_kills_bedwars: number;
    magic_kills_bedwars: number;
    'permanent _items_purchased_bedwars': number;
    permanent_items_purchased_bedwars: number;
    projectile_deaths_bedwars: number;
    resources_collected_bedwars: number;
    suffocation_deaths_bedwars: number;
    two_four__items_purchased_bedwars: number;
    two_four_beds_broken_bedwars: number;
    two_four_beds_lost_bedwars: number;
    two_four_deaths_bedwars: number;
    two_four_entity_attack_deaths_bedwars: number;
    two_four_entity_attack_final_deaths_bedwars: number;
    two_four_entity_attack_final_kills_bedwars: number;
    two_four_entity_attack_kills_bedwars: number;
    two_four_fall_deaths_bedwars: number;
    two_four_final_deaths_bedwars: number;
    two_four_final_kills_bedwars: number;
    two_four_games_played_bedwars: number;
    two_four_gold_resources_collected_bedwars: number;
    two_four_iron_resources_collected_bedwars: number;
    two_four_items_purchased_bedwars: number;
    two_four_kills_bedwars: number;
    two_four_losses_bedwars: number;
    'two_four_permanent _items_purchased_bedwars': number;
    two_four_permanent_items_purchased_bedwars: number;
    two_four_resources_collected_bedwars: number;
    two_four_void_deaths_bedwars: number;
    two_four_void_final_deaths_bedwars: number;
    two_four_void_kills_bedwars: number;
    two_four_wins_bedwars: number;
    two_four_winstreak: number;
    void_deaths_bedwars: number;
    void_final_deaths_bedwars: number;
    void_final_kills_bedwars: number;
    void_kills_bedwars: number;
    wins_bedwars: number;
    winstreak: number;
  }

  export interface SkyBlock {
    profiles: { [key: string]: SkyblockProfile };
  }

  export interface SkyblockProfile {
    profile_id: string;
    cute_name: string;
  }

  export interface SkyClash {
    coins: number;
    card_packs: number;
  }

  export interface SkyWarClass {
    recent?: Prestigious[];
    prestigious?: Prestigious[];
    'FLINT_AND_STEEL:0'?: string;
    'POTION:3'?: string;
    'LAVA_BUCKET:0'?: string;
    'IRON_CHESTPLATE:0'?: string;
    'LEATHER_CHESTPLATE:0'?: string;
    'POTION:12'?: string;
    'LEATHER_LEGGINGS:0'?: string;
    'MONSTER_EGG:65'?: string;
    'IRON_BOOTS:0'?: string;
    'LEATHER_HELMET:0'?: string;
  }

  export interface Prestigious {
    uuid: string;
    timestamp: number;
    mode: 'solo_insane' | 'teams_insane';
    sacrifice: string;
  }

  export interface SpeedUHC {
    firstJoinLobbyInt: number;
    coins: number;
    score: number;
    movedOver: boolean;
    killstreak: number;
    blocks_broken: number;
    blocks_placed: number;
    deaths: number;
    deaths_kit_basic_normal_default: number;
    deaths_mastery_wild_specialist: number;
    deaths_normal: number;
    deaths_team: number;
    deaths_team_normal: number;
    losses: number;
    losses_kit_basic_normal_default: number;
    losses_mastery_wild_specialist: number;
    losses_normal: number;
    losses_team: number;
    losses_team_normal: number;
    quits: number;
    survived_players: number;
    survived_players_kit_basic_normal_default: number;
    survived_players_normal: number;
    survived_players_team: number;
    win_streak: number;
    packages: string[];
    activeKit_NORMAL: string;
    deaths_kit_basic_normal_healer: number;
    deaths_solo: number;
    deaths_solo_normal: number;
    losses_kit_basic_normal_healer: number;
    losses_solo: number;
    losses_solo_normal: number;
    survived_players_kit_basic_normal_healer: number;
    survived_players_solo: number;
    highestKillstreak: number;
    items_enchanted: number;
    kills: number;
    kills_kit_basic_normal_healer: number;
    kills_mastery_wild_specialist: number;
    kills_monthly_a: number;
    kills_normal: number;
    kills_solo: number;
    kills_solo_normal: number;
    kills_weekly_b: number;
    score_kit_basic_normal_healer: number;
    score_normal: number;
    score_solo: number;
  }

  export interface SuperSmash {
    lastLevel_THE_BULK: number;
    smashLevel: number;
    win_streak: number;
    losses_2v2: number;
    coins: number;
    losses_weekly_a: number;
    games_weekly_a: number;
    losses_monthly_b: number;
    losses: number;
    games_2v2: number;
    games_monthly_b: number;
    class_stats: ClassStats;
    quits: number;
    games: number;
    deaths_2v2: number;
    damage_dealt: number;
    smashed_2v2: number;
    damage_dealt_2v2: number;
    smashed: number;
    deaths: number;
    active_class: string;
    lastLevel_GENERAL_CLUCK: number;
    smasher_2v2: number;
    smasher: number;
    kills_2v2: number;
    kills_monthly_b: number;
    kills: number;
    kills_weekly_a: number;
    games_monthly_a: number;
    losses_monthly_a: number;
    xp_CAKE_MONSTER: number;
    lastLevel_CAKE_MONSTER: number;
    wins_2v2: number;
    kills_monthly_a: number;
    wins: number;
    wins_weekly_a: number;
    wins_monthly_a: number;
    xp_THE_BULK: number;
    smash_level_total: number;
    xp_GENERAL_CLUCK: number;
    FRIENDS_gamesDay: number;
    FRIENDS_firstGame: number;
    assists: number;
    assists_normal: number;
    damage_dealt_normal: number;
    deaths_normal: number;
    friend_losses: number;
    friend_losses_normal: number;
    friend_wins: number;
    friend_wins_normal: number;
    games_normal: number;
    kills_normal: number;
    losses_normal: number;
    one_v_one_losses: number;
    one_v_one_losses_normal: number;
    one_v_one_wins: number;
    one_v_one_wins_normal: number;
    smashed_normal: number;
    smasher_normal: number;
    wins_normal: number;
    lastLevel_BOTMUN: number;
    xp_BOTMUN: number;
  }

  export interface ClassStats {
    THE_BULK: TheBulk;
    GENERAL_CLUCK: GeneralCluck;
    CAKE_MONSTER: CakeMonster;
    BOTMUN: Botmun;
  }

  export interface Botmun {
    batarang: Batarang;
    botmubile: Botmubile;
    damage_dealt: number;
    damage_dealt_normal: number;
    friend_losses: number;
    friend_losses_normal: number;
    games: number;
    games_normal: number;
    grappling_hook: Botmubile;
    melee: BOTMUNMelee;
    reinforcements: SeismicSlamClass;
    smashed: number;
    smashed_normal: number;
    bazooka: SeismicSlamClass;
    seismic_slam: SeismicSlamClass;
    smasher: number;
    smasher_normal: number;
    deaths: number;
    deaths_normal: number;
    kills: number;
    kills_normal: number;
    losses: number;
    losses_normal: number;
  }

  export interface Batarang {
    damage_dealt: number;
    damage_dealt_normal: number;
    smasher: number;
    smasher_normal: number;
    kills: number;
    kills_normal: number;
  }

  export interface SeismicSlamClass {
    smashed: number;
    smashed_normal: number;
  }

  export interface Botmubile {
    damage_dealt: number;
    damage_dealt_normal: number;
  }

  export interface BOTMUNMelee {
    damage_dealt: number;
    damage_dealt_normal: number;
    smashed: number;
    smashed_normal: number;
  }

  export interface CakeMonster {
    cake_storm: CakeStorm;
    swing_pin: CakeStorm;
    damage_dealt: number;
    onion_cannon: OnionCannon;
    smashed_2v2: number;
    melee: CAKEMONSTERMelee;
    smashed: number;
    throw_cake: CakeStorm;
    games: number;
    losses_2v2: number;
    deaths_2v2: number;
    losses: number;
    damage_dealt_2v2: number;
    deaths: number;
    games_2v2: number;
  }

  export interface CakeStorm {
    damage_dealt: number;
    damage_dealt_2v2: number;
  }

  export interface CAKEMONSTERMelee {
    damage_dealt_2v2: number;
    smashed_2v2: number;
    smashed: number;
    damage_dealt: number;
  }

  export interface OnionCannon {
    smashed: number;
    smashed_2v2: number;
  }

  export interface GeneralCluck {
    damage_dealt_2v2: number;
    bazooka: BoulderClass;
    deaths_2v2: number;
    reinforcements: BoulderClass;
    losses_2v2: number;
    games_2v2: number;
    games: number;
    deaths: number;
    smasher_2v2: number;
    losses: number;
    damage_dealt: number;
    smasher: number;
    kills_2v2: number;
    kills: number;
    melee: GENERALCLUCKMelee;
    damage_dealt_normal: number;
    deaths_normal: number;
    egg_bazooka: SeismicSlamClass;
    games_normal: number;
    losses_normal: number;
    smashed: number;
    smashed_normal: number;
  }

  export interface BoulderClass {
    damage_dealt: number;
    damage_dealt_2v2: number;
    kills_2v2: number;
    kills: number;
    smasher_2v2: number;
    smasher: number;
    damage_dealt_normal: number;
  }

  export interface GENERALCLUCKMelee {
    damage_dealt: number;
    damage_dealt_2v2: number;
    damage_dealt_normal: number;
  }

  export interface TheBulk {
    losses_2v2: number;
    losses: number;
    games: number;
    games_2v2: number;
    seismic_slam: GENERALCLUCKMelee;
    boulder: BoulderClass;
    reinforcements: OnionCannon;
    smashed: number;
    damage_dealt_2v2: number;
    damage_dealt: number;
    deaths_2v2: number;
    smashed_2v2: number;
    deaths: number;
    kills: number;
    win_streak: number;
    monster_mash: Monster;
    melee: PurpleMelee;
    win_streak_2v2: number;
    wins: number;
    kills_2v2: number;
    wins_2v2: number;
    monster_charge: Monster;
    smasher_2v2: number;
    flaming_desert_eagle: OnionCannon;
    smasher: number;
    bazooka: OnionCannon;
    friend_losses: number;
    friend_losses_normal: number;
    games_normal: number;
    damage_dealt_normal: number;
    smashed_normal: number;
  }

  export interface PurpleMelee {
    kills: number;
    kills_2v2: number;
    damage_dealt: number;
    damage_dealt_2v2: number;
    smashed_2v2: number;
    smashed: number;
    damage_dealt_normal: number;
    smashed_normal: number;
  }

  export interface Monster {
    damage_dealt: number;
    damage_dealt_2v2: number;
    kills_2v2: number;
    kills: number;
    damage_dealt_normal: number;
  }

  export interface TNTGames {
    coins: number;
    record_tntrun: number;
    capture_class: string;
    kills_capture: number;
    deaths_capture: number;
    assists_capture: number;
    record_pvprun: number;
    votes_Spiral: number;
    kills_tntag: number;
    deaths_bowspleef: number;
    tags_bowspleef: number;
    new_bloodwizard_explode: number;
    new_witherwizard_explode: number;
    new_firewizard_regen: number;
    new_bloodwizard_regen: number;
    new_tntrun_double_jumps: number;
    new_spleef_repulsor: number;
    new_tntag_speedy: number;
    wins: number;
    new_icewizard_regen: number;
    new_pvprun_double_jumps: number;
    packages: string[];
    new_firewizard_explode: number;
    new_witherwizard_regen: number;
    new_spleef_tripleshot: number;
    new_icewizard_explode: number;
    new_spleef_double_jumps: number;
    new_kineticwizard_regen: number;
    new_kineticwizard_explode: number;
    winstreak: number;
    run_potions_splashed_on_players: number;
    deaths_tntrun: number;
    kills_pvprun: number;
    deaths_pvprun: number;
    wizards_selected_class: string;
    new_witherwizard_assists: number;
    points_capture: number;
    new_witherwizard_kills: number;
    new_witherwizard_deaths: number;
    new_kineticwizard_kills: number;
    flags: Flags;
    wins_tntag: number;
  }

  export interface Flags {
    enable_explosive_dash: boolean;
    give_dj_feather: boolean;
    show_tip_holograms: boolean;
    show_tntrun_actionbar_info: boolean;
    show_tnttag_actionbar_info: boolean;
    show_wizards_actionbar_info: boolean;
    show_wizards_cooldown_notifications: boolean;
  }

  export interface TrueCombat {
    packages: string[];
    win_streak: number;
    games: number;
    items_enchanted: number;
    crazywalls_deaths_team_chaos: number;
    deaths: number;
    coins: number;
    losses: number;
    crazywalls_games_team_chaos: number;
    crazywalls_losses_team_chaos: number;
    survived_players: number;
    crazywalls_deaths_team: number;
    crazywalls_losses_team: number;
    crazywalls_games_team: number;
    show_noob_holograms: boolean;
    kills_weekly_a: number;
    crazywalls_kills_monthly_a_team_chaos: number;
    arrows_shot: number;
    kills: number;
    crazywalls_kills_team_chaos: number;
    arrows_hit: number;
    crazywalls_kills_weekly_a_team_chaos: number;
    kills_monthly_a: number;
    live_combat: boolean;
    crazywalls_deaths_solo_chaos: number;
    crazywalls_games_solo_chaos: number;
    crazywalls_kills_monthly_a_solo_chaos: number;
    crazywalls_kills_solo_chaos: number;
    crazywalls_kills_weekly_a_solo_chaos: number;
    crazywalls_losses_solo_chaos: number;
  }

  export interface Uhc {
    coins: number;
    clearup_achievement: boolean;
    saved_stats: boolean;
    equippedKit: string;
    packages: string[];
    perk_bloodcraft_line_a: number;
    perk_engineering_line_a: number;
    perk_bloodcraft_line_b: number;
    perk_bloodcraft_line_c: number;
    perk_apprentice_line_a: number;
    perk_apprentice_line_b: number;
    kit_WORKING_TOOLS: number;
    perk_invention_line_a: number;
    perk_toolsmithing_line_a: number;
    perk_hunter_line_a: number;
    perk_hunter_line_b: number;
    perk_hunter_line_c: number;
    perk_engineering_line_b: number;
    perk_engineering_line_c: number;
    perk_survivalism_line_a: number;
    perk_alchemy_line_a: number;
    kills: number;
    score: number;
    deaths: number;
    heads_eaten: number;
    perk_toolsmithing_line_b: number;
    perk_cooking_line_a: number;
    perk_cooking_line_b: number;
    perk_cooking_line_c: number;
    perk_apprentice_line_c: number;
    perk_weaponsmith_line_a: number;
    perk_weaponsmith_line_c: number;
    perk_weaponsmith_line_b: number;
    perk_armorsmith_line_a: number;
    perk_armorsmith_line_c: number;
    perk_armorsmith_line_b: number;
    perk_enchanting_line_a: number;
    perk_toolsmithing_line_c: number;
    deaths_solo: number;
    ultimates_crafted_solo: number;
  }

  export interface VampireZ {
    updated_stats: boolean;
    coins: number;
    human_deaths: number;
    vampire_deaths: number;
    vampire_kills: number;
    zombie_kills: number;
    most_vampire_kills_new: number;
    human_kills: number;
  }

  export interface Walls {
    coins: number;
    deaths: number;
    losses: number;
    kills: number;
    votes_Shire: number;
    Inventory: Inventory;
  }

  export interface Inventory {
    '17': string;
  }

  export interface Walls3 {
    chosen_class: string;
    coins: number;
    deaths: number;
    weeklyDeaths_Herobrine: number;
    weeklyLosses: number;
    weeklyDeaths: number;
    weeklyLosses_Herobrine: number;
    assists: number;
    deaths_Herobrine: number;
    assists_Herobrine: number;
    losses: number;
    losses_Herobrine: number;
    colorblind: boolean;
    packages: string[];
    herobrine_losses: number;
    herobrine_deaths: number;
    chosen_skin_Herobrine: string;
    herobrine_treasures_found_standard: number;
    herobrine_enemies_hit_standard: number;
    treasures_found_standard: number;
    herobrine_a_defender_assists: number;
    herobrine_a_total_kills_standard: number;
    herobrine_enemies_hit: number;
    herobrine_defender_assists_standard: number;
    herobrine_assists: number;
    herobrine_a_activations_standard: number;
    blocks_broken_standard: number;
    potions_drunk_standard: number;
    enemies_hit_standard: number;
    herobrine_meters_walked_speed: number;
    damage_dealt_standard: number;
    meters_walked_speed_standard: number;
    herobrine_potions_drunk_standard: number;
    herobrine_a_assists_standard: number;
    defender_assists_standard: number;
    herobrine_blocks_broken_standard: number;
    herobrine_meters_walked: number;
    herobrine_meters_fallen_standard: number;
    herobrine_games_played: number;
    total_deaths: number;
    final_deaths_standard: number;
    herobrine_potions_drunk: number;
    herobrine_blocks_broken: number;
    herobrine_treasures_found: number;
    herobrine_damage_dealt: number;
    herobrine_blocks_placed_preparation_standard: number;
    herobrine_time_played: number;
    losses_standard: number;
    meters_walked: number;
    herobrine_activations_standard: number;
    meters_fallen_standard: number;
    herobrine_final_deaths_standard: number;
    total_kills: number;
    activations_standard: number;
    herobrine_meters_walked_speed_standard: number;
    potions_drunk: number;
    treasures_found: number;
    blocks_broken: number;
    activations: number;
    blocks_placed: number;
    assists_standard: number;
    herobrine_total_deaths_standard: number;
    herobrine_deaths_standard: number;
    meters_walked_speed: number;
    herobrine_a_damage_dealt: number;
    herobrine_damage_dealt_standard: number;
    herobrine_blocks_placed: number;
    time_played: number;
    herobrine_blocks_placed_preparation: number;
    deaths_standard: number;
    total_deaths_standard: number;
    herobrine_total_kills_standard: number;
    herobrine_losses_standard: number;
    herobrine_a_total_kills: number;
    herobrine_a_enemies_hit_standard: number;
    herobrine_defender_assists: number;
    herobrine_games_played_standard: number;
    herobrine_meters_fallen: number;
    enemies_hit: number;
    final_deaths: number;
    herobrine_a_enemies_hit: number;
    games_played: number;
    blocks_placed_standard: number;
    herobrine_total_deaths: number;
    herobrine_final_deaths: number;
    blocks_placed_preparation: number;
    herobrine_meters_walked_standard: number;
    defender_assists: number;
    meters_fallen: number;
    herobrine_a_defender_assists_standard: number;
    herobrine_a_damage_dealt_standard: number;
    blocks_placed_preparation_standard: number;
    herobrine_assists_standard: number;
    herobrine_time_played_standard: number;
    meters_walked_standard: number;
    herobrine_blocks_placed_standard: number;
    damage_dealt: number;
    games_played_standard: number;
    herobrine_activations: number;
    total_kills_standard: number;
    herobrine_a_activations: number;
    herobrine_total_kills: number;
    time_played_standard: number;
    herobrine_a_assists: number;
    classes: Classes;
    amount_healed: number;
    amount_healed_standard: number;
    iron_ore_broken: number;
    iron_ore_broken_standard: number;
    self_healed: number;
    self_healed_standard: number;
    shark_a_activations: number;
    shark_a_activations_standard: number;
    shark_activations: number;
    shark_activations_standard: number;
    shark_amount_healed: number;
    shark_amount_healed_standard: number;
    shark_assists: number;
    shark_assists_standard: number;
    shark_blocks_broken: number;
    shark_blocks_broken_standard: number;
    shark_blocks_placed: number;
    shark_blocks_placed_preparation: number;
    shark_blocks_placed_preparation_standard: number;
    shark_blocks_placed_standard: number;
    shark_c_amount_healed: number;
    shark_c_amount_healed_standard: number;
    shark_c_self_healed: number;
    shark_c_self_healed_standard: number;
    shark_deaths: number;
    shark_deaths_standard: number;
    shark_defender_assists: number;
    shark_defender_assists_standard: number;
    shark_final_deaths: number;
    shark_final_deaths_standard: number;
    shark_games_played: number;
    shark_games_played_standard: number;
    shark_iron_ore_broken: number;
    shark_iron_ore_broken_standard: number;
    shark_losses: number;
    shark_losses_standard: number;
    shark_meters_fallen: number;
    shark_meters_fallen_standard: number;
    shark_meters_walked: number;
    shark_meters_walked_speed: number;
    shark_meters_walked_speed_standard: number;
    shark_meters_walked_standard: number;
    shark_potions_drunk: number;
    shark_potions_drunk_standard: number;
    shark_self_healed: number;
    shark_self_healed_standard: number;
    shark_time_played: number;
    shark_time_played_standard: number;
    shark_total_deaths: number;
    shark_total_deaths_standard: number;
    shark_total_kills: number;
    shark_total_kills_standard: number;
    shark_treasures_found: number;
    shark_treasures_found_standard: number;
    arrows_fired: number;
    arrows_fired_standard: number;
    arrows_hit: number;
    arrows_hit_standard: number;
    food_eaten: number;
    food_eaten_standard: number;
    golden_apples_eaten: number;
    golden_apples_eaten_standard: number;
    hunter_a_activations: number;
    hunter_a_activations_standard: number;
    hunter_activations: number;
    hunter_activations_standard: number;
    hunter_arrows_fired: number;
    hunter_arrows_fired_standard: number;
    hunter_arrows_hit: number;
    hunter_arrows_hit_standard: number;
    hunter_assists: number;
    hunter_assists_standard: number;
    hunter_b_assists: number;
    hunter_b_assists_standard: number;
    hunter_b_total_kills: number;
    hunter_b_total_kills_standard: number;
    hunter_blocks_broken: number;
    hunter_blocks_broken_standard: number;
    hunter_blocks_placed: number;
    hunter_blocks_placed_preparation: number;
    hunter_blocks_placed_preparation_standard: number;
    hunter_blocks_placed_standard: number;
    hunter_deaths: number;
    hunter_deaths_standard: number;
    hunter_final_deaths: number;
    hunter_final_deaths_standard: number;
    hunter_food_eaten: number;
    hunter_food_eaten_standard: number;
    hunter_games_played: number;
    hunter_games_played_standard: number;
    hunter_golden_apples_eaten: number;
    hunter_golden_apples_eaten_standard: number;
    hunter_iron_ore_broken: number;
    hunter_iron_ore_broken_standard: number;
    hunter_losses: number;
    hunter_losses_standard: number;
    hunter_meters_fallen: number;
    hunter_meters_fallen_standard: number;
    hunter_meters_walked: number;
    hunter_meters_walked_speed: number;
    hunter_meters_walked_speed_standard: number;
    hunter_meters_walked_standard: number;
    hunter_time_played: number;
    hunter_time_played_standard: number;
    hunter_total_deaths: number;
    hunter_total_deaths_standard: number;
    hunter_total_kills: number;
    hunter_total_kills_standard: number;
    hunter_wood_chopped: number;
    hunter_wood_chopped_standard: number;
    wood_chopped: number;
    wood_chopped_standard: number;
  }

  export interface Classes {
    herobrine: Walls3Class;
    enderman: Walls3Class;
    zombie: Walls3Class;
    skeleton: Walls3Class;
  }

  export interface Walls3Class {
    unlocked: boolean;
    checked4: boolean;
    skill_level_d: number;
    skill_level_dChecked5: boolean;
  }

  export interface Tourney {
    first_join_lobby: number;
    mcgo_defusal_0: Tournament;
    total_tributes: number;
    bedwars_two_four_0: Tournament;
    bedwars4s_1: Tournament;
    blitz_duo_1: Tournament;
    grinch_simulator_0: Tournament;
  }

  export interface Tournament {
    games_played?: number;
    playtime: number;
    tributes_earned: number;
    first_win: number;
    seenRPbook?: boolean;
  }
}
